source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FireRoutes_Tests', :exclusive => true do
  pod 'Quick'
  pod 'Nimble'
  pod "FireRoutes", :path => "../"
  pod 'AlamofireObjectMapper'
end
